apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# Kind-specific patches
patches:
  # Convert app service to NodePort for local access
  - target:
      kind: Service
      name: expenses-tracker
    patch: |-
      - op: replace
        path: /spec/type
        value: NodePort
      - op: add
        path: /spec/ports/0/nodePort
        value: 30080
