apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: expenses

labels:
  - pairs:
      app.kubernetes.io/managed-by: argocd
    includeSelectors: true

resources:
  - namespace.yaml
  - mysql-secret.yaml
  - mysql-service.yaml
  - mysql-statefulset.yaml
  - app-deployment.yaml
  - app-service.yaml

images:
  - name: sudarshan0907/expenses-tracker
    newTag: 8e69a6b
