apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: expenses
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: expenses-tracker
type: Opaque
# NOTE: In production, use Sealed Secrets or External Secrets Operator.
# These are base64-encoded values for the learning environment.
# echo -n 'value' | base64
data:
  mysql-root-password: RXhwVHJAY2tlcjIwMjQh       # ExpTr@cker2024!
  mysql-database: ZXhwZW5zZXNfdHJhY2tlcg==         # expenses_tracker
  mysql-username: cm9vdA==                           # root
